### ISSUE TITLE
Customise form site attributes doesn't seem to work 

### ISSUE THREAD

**Issue by gurugeek** [timmyomahony/django-pagedown#80]
I tried 
```
  models.TextField: {'widget': AdminPagedownWidget(attrs={'rows':20, 'cols':200,
                                                   'style': ' font-size: 1.2em;'
                                                    })},
```

but doesn't seem to work (it does for the font but not for the tows and columns. Thanks in advance for your help

**Comment by timmyomahony** [comment]
The plugin is using the same approach to generate attributes as the Django:

https://github.com/django/django/blob/master/django/forms/templates/django/forms/widgets/attrs.html

So I'm curious as to why `rows` and `cols` aren't being rendered. I'll have to investigate further.

**Comment by timmyomahony** [comment]
Just to follow up on this. I tested and the attributes _are_ getting applied for me, but the admin css styling is overwriting their values. 

For example, In my form I tried:

```py
example = forms.CharField(
        widget=AdminPagedownWidget(attrs={'rows': 2}), max_length=500)
```

Which rendered:

```html
<textarea name="example" cols="40" rows="2" class="vLargeTextField wmd-input" maxlength="500" required="" id="wmd-input-id_example"></textarea>
```

You'll see that `rows=2` is included.

The issue is that the height of the input is actually set in the `demo.css` that is included in the widget. This `demo.css` file is coming from the official Pagedown repo that I've included as a submodule. You can see it here:

https://github.com/StackExchange/pagedown/blob/32c0bdb121de04e0e956ddde0391022644ff1a76/demo/browser/demo.css#L27

We're also adding our own local stylesheet to add to that default stylesheet here:

https://github.com/timmyomahony/django-pagedown/blob/master/pagedown/static/admin/css/pagedown.css

This file deals with styling it for Django admin

The solution is to either overwrite the widget and add your own additional stylesheets, or maybe just copy and overwrite the `/pagedown/static/admin/css/pagedown.css` file mentioned above so that your version is copied instead of the library version
